version: '3'

services:
  myapp:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    command: uwsgi --socket 0.0.0.0:7777 --protocol=http -w wsgi:app
    volumes:
      - ./logs:/logs

  celery:
    network_mode: "host"
    build: .
    command: celery worker -B -l info --app=myapp
    volumes:
      - ./logs:/logs
    env_file:
      - .env