version: '3'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: uwsgi --socket 0.0.0.0:5000 --protocol=http -w wsgi:app
    environment:
      - FLASK_APP=myapp/app
    env_file:
    - ./.env_docker
