"""add first_name for users

Revision ID: 0b44ef6fa08d
Revises: 9aa00f287311
Create Date: 2020-03-14 18:11:15.652358

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "0b44ef6fa08d"
down_revision = "9aa00f287311"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("first_name", sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
