"""remove password

Revision ID: 08b560f7cc63
Revises: e47592c02808
Create Date: 2020-03-10 07:41:26.798361

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "08b560f7cc63"
down_revision = "e47592c02808"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
